/**
 * spec-io.mjs — filesystem + spec helpers shared by the pipeline.
 *
 * Zero external dependencies (Node 22 ESM only) so the whole toolchain runs in
 * CI on a bare `npm ci` without pulling generator packages. JSON is the canonical
 * intermediate format; Fineract publishes an OpenAPI JSON document, and keeping a
 * single format keeps the diff/normalize steps deterministic.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const HERE = dirname(fileURLToPath(import.meta.url));
export const TOOL_ROOT = resolve(HERE, '..');
export const REPO_ROOT = resolve(TOOL_ROOT, '..', '..');

export function repoPath(...parts) {
  return resolve(REPO_ROOT, ...parts);
}

export function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function readJsonIfExists(path) {
  return existsSync(path) ? readJson(path) : null;
}

/** Deterministic JSON write: sorted keys ⇒ stable diffs across runs. */
export function writeJson(path, obj) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(sortKeys(obj), null, 2) + '\n', 'utf8');
}

export function writeText(path, text) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text.endsWith('\n') ? text : text + '\n', 'utf8');
}

/** Recursively sort object keys (arrays kept in order — order is semantic there). */
export function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === 'object') {
    return Object.keys(value)
      .sort()
      .reduce((acc, k) => {
        acc[k] = sortKeys(value[k]);
        return acc;
      }, {});
  }
  return value;
}

/** Standard banner emitted at the top of every generated artefact. */
export function generatedBanner(source) {
  return [
    '/**',
    ' * AUTO-GENERATED by tools/api-automation — DO NOT EDIT BY HAND.',
    ` * Source: ${source}`,
    ' * Regenerate: `npm run api:all` (or the weekly GitHub Actions workflow).',
    ' * Hand edits are overwritten on the next contract sync.',
    ' */',
  ].join('\n');
}

const log = (...a) => console.log('[api-automation]', ...a);
export { log };
