#!/usr/bin/env node
/**
 * Phase 3 (partial) — auto-generate E2E specs from the contract.
 *
 * SCOPE, DELIBERATELY LIMITED:
 *  1. Read-only smoke tests for every MATCHED contract operation that is a
 *     GET with zero path parameters. These are safe to call blind (no fixture
 *     data needed, no side effects) and catch exactly the class of drift the
 *     static report can't: wrong status codes, renamed/removed routes,
 *     permission regressions, auth-header handling — at runtime, against a
 *     real Fineract instance.
 *  2. Required-field negative-validation tests for every MATCHED write
 *     operation whose contract `required[]` list is non-empty AND that also
 *     has zero path parameters (so no parent-resource fixture is needed).
 *     Fineract's OpenAPI spec marks `required` on the request body for only a
 *     minority of operations (29 of 313 with any validator rule at all, as of
 *     2026-08-02) — most Fineract request bodies are documented as fully
 *     optional even though the server enforces requirements at runtime. This
 *     generator can only assert what the CONTRACT states; it does not attempt
 *     to reverse-engineer undocumented runtime requirements.
 *
 * OUT OF SCOPE (not attempted here — do NOT assume these exist):
 *  - Happy-path CREATE/UPDATE/DELETE flows. Constructing a valid request body
 *    for an arbitrary Fineract resource requires real domain knowledge
 *    (foreign keys, product config, valid enum combinations) that isn't
 *    recoverable from the contract alone. That's what the hand-written
 *    tests-e2e/isolated/*.spec.mjs lifecycle suite is for — this generator
 *    complements it, it doesn't replace it.
 *  - GET operations that take a path parameter (e.g. `/clients/{id}`) — no
 *    generic way to obtain a valid, safe ID without a prior create step.
 *
 * A handful of the required-field negative tests target global/system-wide
 * config endpoints (business date, cache, currencies, instance-mode). Sending
 * an intentionally-invalid (empty) body should fail validation before any
 * mutation happens — but review before running against anything other than
 * the disposable per-run stack.
 *
 * Regenerate: `npm run api:e2e-gen` (or `node tools/api-automation/generate-e2e.mjs`).
 * Source of truth: contracts/api-drift.json (matchedOps) + generated contracts/validators.
 * Hand edits to the generated *.spec.mjs files are overwritten on next run — put
 * fixture-dependent tests in tests-e2e/isolated/ instead.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const DRIFT_JSON = path.join(ROOT, 'contracts/api-drift.json');
const GEN_CONTRACTS = path.join(ROOT, 'js/api/generated/contracts.generated.js');
const GEN_VALIDATORS = path.join(ROOT, 'js/api/generated/validators.generated.js');
const OUT_DIR = path.join(ROOT, 'tests-e2e/generated');

function loadRules() {
  const src = fs.readFileSync(GEN_VALIDATORS, 'utf8');
  const m = src.match(/const RULES = (\{[\s\S]*?\});/);
  if (!m) throw new Error('Could not locate RULES object in validators.generated.js');
  // eslint-disable-next-line no-eval
  return eval('(' + m[1] + ')');
}

function segmentOf(fineractPath) {
  return fineractPath.replace(/^\/v1\//, '').split('/')[0] || 'root';
}

const HEADER = (extra, imports) => `/**
 * AUTO-GENERATED by tools/api-automation/generate-e2e.mjs — DO NOT EDIT BY HAND.
 * Regenerate: \`npm run api:e2e-gen\`. Hand edits are overwritten on the next run.
 * ${extra}
 */
import { test } from '@playwright/test';
import { ${imports} } from './helpers-shared.mjs';
`;

async function main() {
  if (!fs.existsSync(DRIFT_JSON)) {
    throw new Error('Missing contracts/api-drift.json — run `npm run api:drift` first.');
  }
  const drift = JSON.parse(fs.readFileSync(DRIFT_JSON, 'utf8'));
  const matchedIds = new Set((drift.matchedOps || []).map((o) => o.operationId));
  if (matchedIds.size === 0) {
    throw new Error('contracts/api-drift.json has no matchedOps — regenerate with the current api-drift.mjs.');
  }

  const mod = await import(pathToFileURL(GEN_CONTRACTS).href);
  const CONTRACTS = mod.CONTRACTS || {};
  const RULES = loadRules();

  fs.mkdirSync(OUT_DIR, { recursive: true });

  // --- shared helper (hand-maintained, not regenerated) -------------------
  const helperPath = path.join(OUT_DIR, 'helpers-shared.mjs');
  if (!fs.existsSync(helperPath)) {
    fs.writeFileSync(helperPath, `import { expect } from '@playwright/test';
export const cfg = {
  url: process.env.FINERACT_URL || 'https://127.0.0.1:8443', tenant: process.env.FINERACT_TENANT || 'default',
  user: process.env.FINERACT_USER || 'mifos', pass: process.env.FINERACT_PASS || 'password'
};
function authHeaders() {
  return { 'Fineract-Platform-TenantId': cfg.tenant, Authorization: \`Basic \${Buffer.from(\`\${cfg.user}:\${cfg.pass}\`).toString('base64')}\`, 'Content-Type':'application/json' };
}
export async function fineract(request, method, path) {
  const res = await request.fetch(\`\${cfg.url}/fineract-provider/api/v1\${path}\`, { method, headers: authHeaders(), ignoreHTTPSErrors:true });
  const text = await res.text();
  expect(res.ok(), \`\${method} \${path} -> \${res.status()}\\n\${text}\`).toBeTruthy();
}
export async function fineractExpectRejected(request, method, path, data) {
  const res = await request.fetch(\`\${cfg.url}/fineract-provider/api/v1\${path}\`, { method, headers: authHeaders(), data, ignoreHTTPSErrors:true });
  expect(res.ok(), \`expected \${method} \${path} to be REJECTED for missing required fields, got \${res.status()}\`).toBeFalsy();
}
`);
  }

  // --- 1. read-only GET smoke tests ---------------------------------------
  const getSafe = Object.entries(CONTRACTS)
    .filter(([id, c]) => matchedIds.has(id) && c.method === 'GET' && (!c.pathParams || c.pathParams.length === 0))
    .sort((a, b) => a[0].localeCompare(b[0]));

  const bySegment = new Map();
  for (const [id, c] of getSafe) {
    const seg = segmentOf(c.path);
    if (!bySegment.has(seg)) bySegment.set(seg, []);
    bySegment.get(seg).push([id, c]);
  }

  let getFile = HEADER(
    `Read-only smoke tests: ${getSafe.length} matched, zero-path-param GET operations, ` +
    `grouped by resource (${bySegment.size} groups). Each just confirms the route returns 2xx.`,
    'fineract'
  );
  getFile += `\ntest.describe('generated: read-only GET smoke', () => {\n`;
  for (const [seg, ops] of [...bySegment.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    getFile += `  test.describe('${seg}', () => {\n`;
    getFile += `    test('${ops.length} endpoint${ops.length === 1 ? '' : 's'}', async ({ request }) => {\n`;
    for (const [id, c] of ops) {
      const p = c.path.replace(/^\/v1/, '');
      getFile += `      await test.step(${JSON.stringify(id)}, async () => { await fineract(request, 'GET', ${JSON.stringify(p)}); });\n`;
    }
    getFile += `    });\n  });\n`;
  }
  getFile += `});\n`;
  fs.writeFileSync(path.join(OUT_DIR, 'read-smoke.spec.mjs'), getFile);

  // --- 2. required-field negative-validation tests ------------------------
  const reqSafe = Object.entries(RULES)
    .filter(([id, r]) => matchedIds.has(id) && r.required && r.required.length > 0)
    .filter(([id]) => { const c = CONTRACTS[id]; return c && (!c.pathParams || c.pathParams.length === 0); })
    .sort((a, b) => a[0].localeCompare(b[0]));

  let reqFile = HEADER(
    `Required-field negative-validation: ${reqSafe.length} matched, zero-path-param write operations ` +
    `whose contract declares a non-empty required[] list. Sends an empty body and expects rejection. ` +
    `NOTE: Fineract's spec marks 'required' explicitly on only a minority of operations — this list is ` +
    `NOT exhaustive of what Fineract actually requires at runtime, only of what the contract documents.`,
    'fineractExpectRejected'
  );
  reqFile += `\ntest.describe('generated: required-field validation', () => {\n`;
  for (const [id, r] of reqSafe) {
    const c = CONTRACTS[id];
    const p = c.path.replace(/^\/v1/, '');
    reqFile += `  test(${JSON.stringify(`${id} rejects empty body (missing: ${r.required.join(', ')})`)}, async ({ request }) => {\n`;
    reqFile += `    await fineractExpectRejected(request, ${JSON.stringify(c.method)}, ${JSON.stringify(p)}, {});\n`;
    reqFile += `  });\n`;
  }
  reqFile += `});\n`;
  fs.writeFileSync(path.join(OUT_DIR, 'required-field-validation.spec.mjs'), reqFile);

  console.log(`Generated ${getSafe.length} GET smoke tests across ${bySegment.size} resource groups -> tests-e2e/generated/read-smoke.spec.mjs`);
  console.log(`Generated ${reqSafe.length} required-field validation tests -> tests-e2e/generated/required-field-validation.spec.mjs`);
  console.log(`(${Object.keys(CONTRACTS).length - matchedIds.size} contract ops are not matched/covered and were correctly excluded — see contracts/api-drift.md.)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
