import { test, expect } from '@playwright/test';
import { cfg, fineract, login, runId, date } from './helpers.mjs';
const state={officeId:null,clientId:null,productId:null,accountId:null};
const suffix=String(runId).replace(/\D/g,'').slice(-8); const rows=v=>v?.pageItems||(Array.isArray(v)?v:[]);
async function raw(request,method,path,data){return request.fetch(`${cfg.url}/fineract-provider/api/v1${path}`,{method,data,ignoreHTTPSErrors:true,headers:{'Fineract-Platform-TenantId':cfg.tenant,Authorization:`Basic ${Buffer.from(`${cfg.user}:${cfg.pass}`).toString('base64')}`,'Content-Type':'application/json'}})}
async function optional(request,method,path,data){const r=await raw(request,method,path,data);const t=await r.text();let b={};try{b=t?JSON.parse(t):{}}catch{b={raw:t}}return{supported:r.ok(),status:r.status(),body:b}}
async function createAccount(request,label){const x=await fineract(request,'POST','/accounts/share',{clientId:state.clientId,productId:state.productId,requestedShares:10,submittedDate:date(),externalId:`FC-SH-${label}-${runId}`.slice(0,50),dateFormat:'dd MM yyyy',locale:'en'});return x.resourceId||x.savingsId}
test.describe.serial('module 17 - shares lifecycle',()=>{
 test('create client and share product prerequisites',async({request})=>{state.officeId=rows(await fineract(request,'GET','/offices'))[0]?.id;const c=await fineract(request,'POST','/clients',{officeId:state.officeId,firstname:'FinCraft',lastname:`Shares ${runId}`.slice(0,45),active:true,activationDate:date(),submittedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});state.clientId=c.clientId||c.resourceId;const p=await fineract(request,'POST','/products/share',{name:`FinCraft Shares ${runId}`.slice(0,90),shortName:`FS${suffix}`.slice(0,20),currencyCode:'USD',digitsAfterDecimal:2,inMultiplesOf:1,totalShares:10000,sharesIssued:10000,unitPrice:10,minimumShares:1,nominalShares:10,maximumShares:100,defaultShares:10,accountingRule:1,locale:'en',dateFormat:'dd MM yyyy'});state.productId=p.resourceId;expect(state.clientId&&state.productId).toBeTruthy()});
 test('submit retrieve update approve and activate share account',async({request})=>{state.accountId=await createAccount(request,'MAIN');expect(state.accountId).toBeTruthy();await fineract(request,'GET',`/accounts/share/${state.accountId}`);await fineract(request,'PUT',`/accounts/share/${state.accountId}`,{requestedShares:12,externalId:`FC-SH-UP-${runId}`.slice(0,50),dateFormat:'dd MM yyyy',locale:'en'});await fineract(request,'POST',`/accounts/share/${state.accountId}?command=approve`,{approvedDate:date(),dateFormat:'dd MM yyyy',locale:'en'});const act=await optional(request,'POST',`/accounts/share/${state.accountId}?command=activate`,{activatedDate:date(),dateFormat:'dd MM yyyy',locale:'en'});test.info().annotations.push({type:'activation',description:act.supported?'SUPPORTED':`NOT APPLICABLE HTTP ${act.status}`})});
 test('apply additional shares approve request and redeem shares',async({request})=>{const add=await optional(request,'POST',`/accounts/share/${state.accountId}?command=applyadditionalshares`,{requestedShares:3,requestedDate:date(),dateFormat:'dd MM yyyy',locale:'en'});if(add.supported){const s=await fineract(request,'GET',`/accounts/share/${state.accountId}`);const req=(s.purchasedShares||s.requestedShares||[]).find(x=>!x.status||!/approved/i.test(x.status?.value||''));if(req?.id)await optional(request,'POST',`/accounts/share/${state.accountId}?command=approveshare`,{requestedShares:[{id:req.id}],dateFormat:'dd MM yyyy',locale:'en'})}const redeem=await optional(request,'POST',`/accounts/share/${state.accountId}?command=redeemshares`,{requestedShares:1,requestedDate:date(),dateFormat:'dd MM yyyy',locale:'en'});test.info().annotations.push({type:'additional-redeem',description:`additional=${add.status}, redeem=${redeem.status}`})});
 test('dividend lifecycle is capability-tested',async({request})=>{const div=await optional(request,'POST',`/shareproduct/${state.productId}/dividend`,{dividendPeriodStartDate:date(),dividendPeriodEndDate:date(),dividendAmount:10,dateFormat:'dd MM yyyy',locale:'en'});if(div.supported&&div.body.resourceId){const id=div.body.resourceId;await fineract(request,'GET',`/shareproduct/${state.productId}/dividend/${id}`);await optional(request,'PUT',`/shareproduct/${state.productId}/dividend/${id}`,{dividendAmount:12,dateFormat:'dd MM yyyy',locale:'en'});await optional(request,'PUT',`/shareproduct/${state.productId}/dividend/${id}?command=approve`,{});}test.info().annotations.push({type:'dividend',description:div.supported?'CREATED':`NOT APPLICABLE HTTP ${div.status}`})});
 test('reject withdraw undo approval and delete disposable applications',async({request})=>{for(const [label,cmd,field] of [['REJECT','reject','rejectedDate'],['WITHDRAW','withdrawnByApplicant','withdrawnDate']]){const id=await createAccount(request,label);await fineract(request,'POST',`/accounts/share/${id}?command=${cmd}`,{[field]:date(),dateFormat:'dd MM yyyy',locale:'en'})}const id=await createAccount(request,'UNDO');await fineract(request,'POST',`/accounts/share/${id}?command=approve`,{approvedDate:date(),dateFormat:'dd MM yyyy',locale:'en'});await optional(request,'POST',`/accounts/share/${id}?command=undoapproval`,{});const disposable=await createAccount(request,'DELETE');await fineract(request,'DELETE',`/accounts/share/${disposable}`)});
 test('share list and detail render through FinCraft',async({page})=>{await login(page);await page.evaluate(async()=>{const r=await import('/js/router.js');r.navigate('shares')});const c=page.locator('#contentArea');await expect(c).toContainText(/Shares|Share Account|FinCraft/i,{timeout:30000});await page.evaluate(async id=>{const r=await import('/js/router.js');r.navigate('share-detail',{id})},state.accountId);await expect(c).toContainText(/Share|FinCraft/i,{timeout:30000});await expect(c).not.toContainText(/Cannot read properties|is not defined|innerHTML of null/i)});
 test('share account remains in portfolio list',async({request})=>{const list=rows(await fineract(request,'GET','/accounts/share?limit=200'));expect(list.some(x=>x.id===state.accountId)).toBeTruthy()});
});
