import { test, expect } from '@playwright/test';
import { cfg, fineract, login, runId, date } from './helpers.mjs';
const state={officeId:null,clientId:null,productId:null,overdraftProductId:null,accountId:null,secondId:null,depositTxId:null};
const suffix=String(runId).replace(/\D/g,'').slice(-8);const rows=v=>v?.pageItems||(Array.isArray(v)?v:[]);
async function raw(request,method,path,data){return request.fetch(`${cfg.url}/fineract-provider/api/v1${path}`,{method,data,ignoreHTTPSErrors:true,headers:{'Fineract-Platform-TenantId':cfg.tenant,Authorization:`Basic ${Buffer.from(`${cfg.user}:${cfg.pass}`).toString('base64')}`,'Content-Type':'application/json'}})}
async function opt(request,method,path,data){const r=await raw(request,method,path,data);const t=await r.text();let b={};try{b=t?JSON.parse(t):{}}catch{b={raw:t}}return{supported:r.ok(),status:r.status(),body:b}}
const tx=amount=>({transactionDate:date(),transactionAmount:amount,paymentTypeId:1,dateFormat:'dd MM yyyy',locale:'en'});
async function createProduct(request,label,overdraft=false){const r=await fineract(request,'POST','/savingsproducts',{name:`FinCraft Savings ${label} ${runId}`.slice(0,90),shortName:`${overdraft?'O':'S'}${suffix}`.slice(0,4),currencyCode:'USD',digitsAfterDecimal:2,inMultiplesOf:1,nominalAnnualInterestRate:5,interestCompoundingPeriodType:4,interestPostingPeriodType:4,interestCalculationType:1,interestCalculationDaysInYearType:365,accountingRule:1,withdrawalFeeForTransfers:false,allowOverdraft:overdraft,overdraftLimit:overdraft?500:undefined,nominalAnnualInterestRateOverdraft:overdraft?10:undefined,minOverdraftForInterestCalculation:overdraft?1:undefined});return r.resourceId}
async function account(request,productId=state.productId){const r=await fineract(request,'POST','/savingsaccounts',{clientId:state.clientId,productId,submittedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});const id=r.savingsId||r.resourceId;await fineract(request,'POST',`/savingsaccounts/${id}?command=approve`,{approvedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});await fineract(request,'POST',`/savingsaccounts/${id}?command=activate`,{activatedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});return id}
test.describe.serial('module 18 - savings extended lifecycle',()=>{
 test('create extended savings prerequisites and funded accounts',async({request})=>{state.officeId=rows(await fineract(request,'GET','/offices'))[0]?.id;const c=await fineract(request,'POST','/clients',{officeId:state.officeId,firstname:'FinCraft',lastname:`Savings Extended ${runId}`.slice(0,45),legalFormId:1,active:true,activationDate:date(),submittedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});state.clientId=c.clientId||c.resourceId;state.productId=await createProduct(request,'Standard');state.overdraftProductId=await createProduct(request,'Overdraft',true);state.accountId=await account(request);state.secondId=await account(request);const d=await fineract(request,'POST',`/savingsaccounts/${state.accountId}/transactions?command=deposit`,tx(1000));state.depositTxId=d.resourceId;await fineract(request,'POST',`/savingsaccounts/${state.secondId}/transactions?command=deposit`,tx(100));expect(state.depositTxId).toBeTruthy()});
 test('savings charge lifecycle uses configured compatible charge',async({request})=>{const tpl=await opt(request,'GET',`/savingsaccounts/${state.accountId}/charges/template`);const options=tpl.body?.chargeOptions||tpl.body?.charges||[];const charge=options.find(x=>x.active!==false);if(!charge)test.skip(true,'No configured savings charge');const add=await opt(request,'POST',`/savingsaccounts/${state.accountId}/charges`,{chargeId:charge.id,amount:charge.amount||10,dueDate:date(),dateFormat:'dd MM yyyy',locale:'en'});if(!add.supported)test.skip(true,`Charge add unavailable HTTP ${add.status}`);const id=add.body.resourceId;await fineract(request,'GET',`/savingsaccounts/${state.accountId}/charges/${id}`);await opt(request,'PUT',`/savingsaccounts/${state.accountId}/charges/${id}`,{amount:11,dueDate:date(),dateFormat:'dd MM yyyy',locale:'en'});await opt(request,'POST',`/savingsaccounts/${state.accountId}/charges/${id}?command=paycharge`,tx(11));await opt(request,'POST',`/savingsaccounts/${state.accountId}/charges/${id}?command=waive`,{});await opt(request,'POST',`/savingsaccounts/${state.accountId}/charges/${id}?command=inactivate`,{});await opt(request,'DELETE',`/savingsaccounts/${state.accountId}/charges/${id}`)});
 test('hold and release amount lifecycle',async({request})=>{const hold=await opt(request,'POST',`/savingsaccounts/${state.accountId}/transactions?command=holdAmount`,{transactionDate:date(),transactionAmount:50,dateFormat:'dd MM yyyy',locale:'en'});if(!hold.supported)test.skip(true,`Hold unavailable HTTP ${hold.status}`);const id=hold.body.resourceId;expect(id).toBeTruthy();await fineract(request,'GET',`/savingsaccounts/${state.accountId}/onholdtransactions`);const release=await opt(request,'POST',`/savingsaccounts/${state.accountId}/transactions/${id}?command=releaseAmount`,{});expect(release.supported).toBeTruthy()});
 test('transaction adjustment and undo commands',async({request})=>{const modify=await opt(request,'POST',`/savingsaccounts/${state.accountId}/transactions/${state.depositTxId}?command=modify`,tx(900));test.info().annotations.push({type:'adjustment',description:modify.supported?'SUPPORTED':`UNAVAILABLE HTTP ${modify.status}`});const d=await fineract(request,'POST',`/savingsaccounts/${state.accountId}/transactions?command=deposit`,tx(25));const undo=await opt(request,'POST',`/savingsaccounts/${state.accountId}/transactions/${d.resourceId}?command=undo`,{});test.info().annotations.push({type:'undo',description:undo.supported?'SUPPORTED':`UNAVAILABLE HTTP ${undo.status}`})});
 test('account transfer and standing instruction surfaces',async({request})=>{const template=await opt(request,'GET',`/accounttransfers/template?fromAccountId=${state.accountId}&fromAccountType=2&toAccountId=${state.secondId}&toAccountType=2`);test.info().annotations.push({type:'transfer-template',description:template.supported?'SUPPORTED':`HTTP ${template.status}`});const transfer=await opt(request,'POST','/accounttransfers',{fromOfficeId:state.officeId,fromClientId:state.clientId,fromAccountType:2,fromAccountId:state.accountId,toOfficeId:state.officeId,toClientId:state.clientId,toAccountType:2,toAccountId:state.secondId,transferDate:date(),transferAmount:20,transferDescription:'Module 18 savings transfer',dateFormat:'dd MM yyyy',locale:'en'});test.info().annotations.push({type:'transfer',description:transfer.supported?'CREATED':`HTTP ${transfer.status}`});const si=await opt(request,'GET',`/standinginstructions/template?fromAccountId=${state.accountId}&fromAccountType=2`);test.info().annotations.push({type:'standing-instruction',description:si.supported?'TEMPLATE SUPPORTED':`HTTP ${si.status}`});await opt(request,'GET','/standinginstructions?limit=100');await opt(request,'GET','/standinginstructionrunhistory?limit=100')});
 test('close funded account with withdrawal capability',async({request})=>{const id=await account(request);await fineract(request,'POST',`/savingsaccounts/${id}/transactions?command=deposit`,tx(100));const close=await opt(request,'POST',`/savingsaccounts/${id}?command=close`,{closedOnDate:date(),withdrawBalance:true,paymentTypeId:1,note:'Module 18 close',dateFormat:'dd MM yyyy',locale:'en'});test.info().annotations.push({type:'close-with-withdrawal',description:close.supported?'CLOSED':`HTTP ${close.status}`})});
 test('GSIM group savings capability is executable',async({request})=>{const result=await opt(request,'POST','/savingsaccounts/gsim',{clientId:state.clientId,productId:state.productId,submittedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});test.info().annotations.push({type:'gsim',description:result.supported?'CREATED':`NOT CONFIGURED HTTP ${result.status}`});if(result.supported&&result.body.resourceId)await opt(request,'POST',`/savingsaccounts/gsimcommands/${result.body.resourceId}?command=approve`,{approvedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'})});
 test('overdraft lifecycle permits or explicitly rejects negative balance',async({request})=>{const id=await account(request,state.overdraftProductId);await fineract(request,'POST',`/savingsaccounts/${id}/transactions?command=deposit`,tx(50));const withdrawal=await opt(request,'POST',`/savingsaccounts/${id}/transactions?command=withdrawal`,tx(100));test.info().annotations.push({type:'overdraft-withdrawal',description:withdrawal.supported?'NEGATIVE BALANCE SUPPORTED':`REJECTED HTTP ${withdrawal.status}`});if(withdrawal.supported){const saved=await fineract(request,'GET',`/savingsaccounts/${id}`);expect(Number(saved.summary?.accountBalance)).toBeLessThan(0)}});
 test('extended savings UI surfaces render',async({page})=>{await login(page);const c=page.locator('#contentArea');await page.evaluate(async()=>{const r=await import('/js/router.js');r.navigate('savings')});await expect(c).toContainText(/Savings|FinCraft/i,{timeout:30000});await page.evaluate(async id=>{const r=await import('/js/router.js');r.navigate('savings-detail',{id})},state.accountId);await expect(c).toContainText(/Savings|Transaction|Charge|FinCraft/i,{timeout:30000});await expect(c).not.toContainText(/Cannot read properties|is not defined|innerHTML of null/i)});
});
