import { test, expect } from '@playwright/test';
import { cfg, fineract, login, runId, date } from './helpers.mjs';
const state={officeId:null,clientId:null,productId:null,loanId:null,repaymentTxId:null};
const suffix=String(runId).replace(/\D/g,'').slice(-8);const rows=v=>v?.pageItems||(Array.isArray(v)?v:[]);
async function raw(request,method,path,data){return request.fetch(`${cfg.url}/fineract-provider/api/v1${path}`,{method,data,ignoreHTTPSErrors:true,headers:{'Fineract-Platform-TenantId':cfg.tenant,Authorization:`Basic ${Buffer.from(`${cfg.user}:${cfg.pass}`).toString('base64')}`,'Content-Type':'application/json'}})}
async function opt(request,method,path,data){const r=await raw(request,method,path,data);const t=await r.text();let b={};try{b=t?JSON.parse(t):{}}catch{b={raw:t}}return{supported:r.ok(),status:r.status(),body:b}}
const tx=amount=>({transactionDate:date(),transactionAmount:amount,paymentTypeId:1,dateFormat:'dd MM yyyy',locale:'en'});
async function createLoan(request,disburse=true){const r=await fineract(request,'POST','/loans',{clientId:state.clientId,productId:state.productId,loanType:'individual',principal:1000,numberOfRepayments:6,repaymentEvery:1,repaymentFrequencyType:2,interestRatePerPeriod:12,amortizationType:1,interestType:0,interestCalculationPeriodType:1,transactionProcessingStrategyCode:'mifos-standard-strategy',submittedOnDate:date(),expectedDisbursementDate:date(),dateFormat:'dd MM yyyy',locale:'en'});const id=r.loanId||r.resourceId;await fineract(request,'POST',`/loans/${id}?command=approve`,{approvedOnDate:date(),approvedLoanAmount:1000,dateFormat:'dd MM yyyy',locale:'en'});if(disburse)await fineract(request,'POST',`/loans/${id}?command=disburse`,{actualDisbursementDate:date(),transactionAmount:1000,paymentTypeId:1,dateFormat:'dd MM yyyy',locale:'en'});return id}
test.describe.serial('module 19 - loans extended lifecycle',()=>{
 test('create active loan prerequisites',async({request})=>{state.officeId=rows(await fineract(request,'GET','/offices'))[0]?.id;const c=await fineract(request,'POST','/clients',{officeId:state.officeId,firstname:'FinCraft',lastname:`Loans Extended ${runId}`.slice(0,45),legalFormId:1,active:true,activationDate:date(),submittedOnDate:date(),dateFormat:'dd MM yyyy',locale:'en'});state.clientId=c.clientId||c.resourceId;const p=await fineract(request,'POST','/loanproducts',{name:`FinCraft Loan Extended ${runId}`.slice(0,90),shortName:`LX${suffix}`.slice(0,20),currencyCode:'USD',digitsAfterDecimal:2,inMultiplesOf:1,principal:1000,minPrincipal:100,maxPrincipal:5000,numberOfRepayments:6,minNumberOfRepayments:1,maxNumberOfRepayments:24,repaymentEvery:1,repaymentFrequencyType:2,interestRatePerPeriod:12,interestRateFrequencyType:3,amortizationType:1,interestType:0,interestCalculationPeriodType:1,transactionProcessingStrategyCode:'mifos-standard-strategy',accountingRule:1});state.productId=p.resourceId;state.loanId=await createLoan(request);expect(state.loanId).toBeTruthy()});
 test('loan charge lifecycle uses configured compatible charge',async({request})=>{const tpl=await opt(request,'GET',`/loans/${state.loanId}/charges/template`);const options=tpl.body?.chargeOptions||tpl.body?.charges||[];const charge=options.find(x=>x.active!==false);if(!charge)test.skip(true,'No compatible loan charge configured');const add=await opt(request,'POST',`/loans/${state.loanId}/charges`,{chargeId:charge.id,amount:charge.amount||10,dueDate:date(),dateFormat:'dd MM yyyy',locale:'en'});if(!add.supported)test.skip(true,`Charge add unavailable HTTP ${add.status}`);const id=add.body.resourceId;await fineract(request,'GET',`/loans/${state.loanId}/charges/${id}`);await opt(request,'PUT',`/loans/${state.loanId}/charges/${id}`,{amount:11,dueDate:date(),dateFormat:'dd MM yyyy',locale:'en'});await opt(request,'POST',`/loans/${state.loanId}/charges/${id}?command=paycharge`,tx(11));await opt(request,'POST',`/loans/${state.loanId}/charges/${id}?command=waive`,{});await opt(request,'POST',`/loans/${state.loanId}/charges/${id}?command=adjustment`,{amount:1,locale:'en'});await opt(request,'DELETE',`/loans/${state.loanId}/charges/${id}`)});
 test('collateral and guarantor CRUD capability',async({request})=>{for(const [name,path] of [['collateral',`/loans/${state.loanId}/collaterals/template`],['guarantor',`/loans/${state.loanId}/guarantors/template`],['guarantor-accounts',`/loans/${state.loanId}/guarantors/accounts/template`]]){const r=await opt(request,'GET',path);test.info().annotations.push({type:name,description:r.supported?'TEMPLATE SUPPORTED':`HTTP ${r.status}`})}await opt(request,'GET',`/loans/${state.loanId}/collaterals`);await opt(request,'GET',`/loans/${state.loanId}/guarantors`)});
 test('repayment adjustment prepayment refund and chargeback commands',async({request})=>{const repayment=await fineract(request,'POST',`/loans/${state.loanId}/transactions?command=repayment`,tx(100));state.repaymentTxId=repayment.resourceId;for(const [name,path,body] of [['adjust',`/loans/${state.loanId}/transactions/${state.repaymentTxId}?command=adjust`,tx(90)],['chargeback',`/loans/${state.loanId}/transactions/${state.repaymentTxId}?command=chargeback`,tx(10)],['prepay',`/loans/${state.loanId}/transactions?command=prepayLoan`,tx(10)],['refund-cash',`/loans/${state.loanId}/transactions?command=refundByCash`,tx(5)],['credit-refund',`/loans/${state.loanId}/transactions?command=creditBalanceRefund`,tx(5)]]) { const r=await opt(request,'POST',path,body);test.info().annotations.push({type:name,description:r.supported?'SUPPORTED':`HTTP ${r.status}`})}});
 test('write-off charge-off foreclosure recovery and undo surfaces',async({request})=>{for(const [name,cmd] of [['writeoff','writeoff'],['charge-off','charge-off'],['foreclosure','foreclosure'],['recovery','recoverypayment']]){const id=await createLoan(request);const r=await opt(request,'POST',`/loans/${id}/transactions?command=${cmd}`,tx(name==='recovery'?10:1000));test.info().annotations.push({type:name,description:r.supported?'SUPPORTED':`HTTP ${r.status}`});if(name==='charge-off'&&r.supported)await opt(request,'POST',`/loans/${id}/transactions?command=undo-charge-off`,{})}});
 test('reschedule re-age and re-amortization operations',async({request})=>{const tpl=await opt(request,'GET',`/rescheduleloans/template?loanId=${state.loanId}`);test.info().annotations.push({type:'reschedule-template',description:tpl.supported?'SUPPORTED':`HTTP ${tpl.status}`});for(const [name,path] of [['reage-preview',`/loans/${state.loanId}/transactions/reage-preview`],['reamortize-preview',`/loans/${state.loanId}/transactions/reamortization-preview`],['pending-reschedules',`/rescheduleloans?loanId=${state.loanId}&command=pending`]]){const r=await opt(request,'GET',path);test.info().annotations.push({type:name,description:r.supported?'SUPPORTED':`HTTP ${r.status}`})}});
 test('multi-tranche disbursement-to-savings top-up and GLIM surfaces',async({request})=>{for(const [name,path] of [['disbursements',`/loans/${state.loanId}?associations=all`],['glim',`/loans/glimAccount/${state.loanId}`],['loan-template',`/loans/template?clientId=${state.clientId}&productId=${state.productId}`]]){const r=await opt(request,'GET',path);test.info().annotations.push({type:name,description:r.supported?'SUPPORTED':`HTTP ${r.status}`})}const d=await opt(request,'POST',`/loans/${state.loanId}?command=disburseToSavings`,{actualDisbursementDate:date(),transactionAmount:1,dateFormat:'dd MM yyyy',locale:'en'});test.info().annotations.push({type:'disburse-to-savings',description:d.supported?'SUPPORTED':`HTTP ${d.status}`})});
 test('external asset ownership originators and advanced portfolio APIs',async({request})=>{for(const [name,path] of [['eao-transfer',`/external-asset-owners/transfers?loanId=${state.loanId}`],['originators',`/loans/${state.loanId}/originators`],['approved-history',`/loans/${state.loanId}/approved-amount`],['at-date',`/loans/at-date/${state.loanId}`],['locked','/loans/locked'],['catch-up','/loans/is-catch-up-running'],['oldest-cob','/loans/oldest-cob-closed']]){const r=await opt(request,'GET',path);test.info().annotations.push({type:name,description:r.supported?'SUPPORTED':`HTTP ${r.status}`})}});
 test('interest pauses post-dated checks delinquency and advanced income surfaces',async({request})=>{for(const [name,path] of [['interest-pauses',`/loans/${state.loanId}/interest-pauses`],['postdated-checks',`/loans/${state.loanId}/postdatedchecks`],['delinquency-actions',`/loans/${state.loanId}/delinquency-actions`],['delinquency-tags',`/loans/${state.loanId}/delinquencytags`],['buydown-fees',`/loans/${state.loanId}/buydown-fees`],['capitalized-income',`/loans/${state.loanId}/capitalized-incomes`],['deferred-income',`/loans/${state.loanId}/deferredincome`]]){const r=await opt(request,'GET',path);test.info().annotations.push({type:name,description:r.supported?'SUPPORTED':`HTTP ${r.status}`})}});
 test('extended loan UI renders advanced action surfaces',async({page})=>{await login(page);const c=page.locator('#contentArea');await page.evaluate(async()=>{const r=await import('/js/router.js');r.navigate('loans')});await expect(c).toContainText(/Loan|FinCraft/i,{timeout:30000});await page.evaluate(async id=>{const r=await import('/js/router.js');r.navigate('loan-detail',{id})},state.loanId);await expect(c).toContainText(/Loan|Transaction|Charge|Collateral|FinCraft/i,{timeout:30000});await expect(c).not.toContainText(/Cannot read properties|is not defined|innerHTML of null/i)});
});
